# SECTION 1: INPUT
input:

  # Path to the Excel file containing the metadata of the study. See README.md for
  # further details about the accepted file format
  excel_file: '/projects/neuro/AlfaStudy/aging_apoe_data_surface/Data_VBM_Alfa_final.xls'

  # Path to the folder containing the NIFTI files with the grey matter values for each subject
  data_folder: '/projects/neuro/AlfaStudy/aging_apoe_data_surface/data/'

  # Path to the Nifti file containing the template used to register the subjects of these project
  template_file: '/projects/neuro/AlfaStudy/aging_apoe_data_surface/fsaverage/surf/lh.inflated'

  # Study prefix, that is, prefix used in every greymatter file (NIFTI) before the identifier.
  # (e.g: if prefix is 'study1_' and a subject has id 'subject1', the corresponding greymatter file would be located
  # inside the folder pointed by data_folder and would be named 'study1_subject1.nii' or 'study1_subject1.nii.gz'
  study_prefix: 'lh_fsaverage_'

  # File extension (str): '.nii', '.nii.gz', 'mgh', '.mgz', '.thickness'
  extension: '.thickness'

# --------------------------------------------------------------------------------------------------------------------

# SECTION 2: MODEL
model:

  # Identifier used in the excel file for the column that contains the ID of the subject and type of data used to
  # express this identifier (String, Number)
  id_identifier: 'Subj_ID'
  id_type: 'Number'

  # Identifier used in the excel file for the column that contains the category/class of the subject.
  # If there is no category identifier for this study, put No
  category_identifier: '# of Apoe4'

  # Identifier that should be used as a predictor
  predictor_identifier:
    - 'Age'

  # List of identifiers that should be used as correctors
  correctors_identifiers:
    - 'Gender(0=female)'
    - 'Years of Education'

# --------------------------------------------------------------------------------------------------------------------

# SECTION 3: CONFIGURATION FOR FINDING HYPERPARAMETERS
hyperparameters_finding:

  # Find epsilon hyperparameter (can be used for PolySVR and GaussianSVR) ?
  epsilon: Yes

  # If epsilon is used, use the start and end values specified below.
  # Note that if linear spacing is used, the search spane will be [start, end], but if logarithmic
  # spacing is used, the search span will be [10 ^ start, 10 ^ end]
  # Available methods: deterministic and random
  epsilon_values:
    spacing: linear
    method: deterministic
    N: 20
    start: 0.005
    end: 0.1

  # Find C (regularization) hyperparameter (can be used for PolySVR and GaussianSVR) ?
  C: Yes

  # If C is used, use the start and end values specified below.
  # Note that if linear spacing is used, the search spane will be [start, end], but if logarithmic
  # spacing is used, the search span will be [10 ^ start, 10 ^ end]
  # Available methods: deterministic and random
  C_values:
    spacing: logarithmic
    method: random
    N: 2
    start: 0
    end: 1

  # Find gamma hyperparameter (can be used for GaussianSVR only) ?
  gamma: Yes

  # If gamma is used, use the start and end values specified below.
  # Note that if linear spacing is used, the search spane will be [start, end], but if logarithmic
  # spacing is used, the search span will be [10 ^ start, 10 ^ end]
  # Available methods: deterministic and random
  gamma_values:
    spacing: linear
    method: deterministic
    N: 10
    start: 0.1
    end: 1

# --------------------------------------------------------------------------------------------------------------------

# SECTION 4: PROCESSING PARAMETERS
processing_params:

  # Number of processes spanned to perform computational-heavy tasks, such as fitting.
  n_jobs: 4

  # Total amount of memory in MB used to get Chunks of gray matter data from all subjects
  # (as memory increases so does the number of voxels used in one chunck)
  mem_usage: 256

  # Total amount of memory in MB used to cache the Gramm matrices used in SVR fitting
  # (more memory implies a speed up in the SVR fitting process)
  cache_size: 2048

# --------------------------------------------------------------------------------------------------------------------

# SECTION 4: OUTPUT
output:

  # Path to the folder where all results will be stored
  output_path: '/imatge/acasamitjana/work/NeAT/surface_proves'
  extension: '.maps'
